"use client";
import React, { useState, useMemo } from "react";
import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer/footer";
import { helveticaCompressed, bigShouldersDisplay } from "@/app/fonts";

const formatContent = (content: string) => {
  if (!content || content.trim() === "") {
    return (
      <p className="text-gray-700 italic">Content will be available soon.</p>
    );
  }

  // Split the content by lines
  const lines = content.split("\n");
  const formattedContent: React.ReactNode[] = [];
  let currentList: string[] = [];
  let key = 0;

  // Process each line
  lines.forEach((line) => {
    const trimmedLine = line.trim();

    // Check if it's a bullet point
    if (trimmedLine.startsWith("•")) {
      // Add to current bullet list
      currentList.push(trimmedLine.substring(1).trim());
    } else {
      // If we have bullet points collected, add the list
      if (currentList.length > 0) {
        formattedContent.push(
          <ul
            key={`list-${key++}`}
            className="list-disc pl-6 mb-4 text-gray-700"
          >
            {currentList.map((item, i) => (
              <li key={`item-${i}`} className="mb-2">
                {item}
              </li>
            ))}
          </ul>
        );
        currentList = [];
      }

      // Add the regular line as a paragraph if it's not empty
      if (trimmedLine && !trimmedLine.startsWith("-")) {
        formattedContent.push(
          <p key={`para-${key++}`} className="text-gray-700 mb-4 font-medium">
            {trimmedLine}
          </p>
        );
      }
    }
  });

  // Handle any remaining bullet points
  if (currentList.length > 0) {
    formattedContent.push(
      <ul key={`list-${key++}`} className="list-disc pl-6 mb-4 text-gray-700">
        {currentList.map((item, i) => (
          <li key={`item-${i}`} className="mb-2">
            {item}
          </li>
        ))}
      </ul>
    );
  }

  return <>{formattedContent}</>;
};

export default function Page() {
  const [activeSection, setActiveSection] = useState(0);

  // Business plan sections with the new titles
  const bplanSections = useMemo(
    () => [
      {
        title: "Marketing Strategies",
        content: `Trust-Building Framework
•	Outline the framework your business will use to build and maintain customer trust across all touchpoints.
•	Address both demographic (age, gender, location) and psychographic (traits, values, goals) segments.
•	Explain how you will engage and earn the trust of your core customer base.
Short-Term Marketing Plan
•	Elaborate on your short-term marketing strategy for the product launch.
•	Detail one specific launch campaign and its objectives.
•	List key KPIs and benchmarks for success (e.g., sign-ups, conversions, visits).
Marketing Channels and Goals
•	Identify the most effective channels to reach your target audience.
•	Set clear, measurable goals aligned with your overall marketing strategy.
Long-Term Marketing Strategy
•	Outline how you plan to sustain and grow your brand over time.
•	Explain how long-term efforts will complement short-term tactics.
•	Include plans for scaling, market expansion, or brand evolution.
Strategic Partnerships and Alliances
•	Discuss any partnerships or alliances that support distribution, marketing, or development.
•	Highlight the benefits and roles of each partnership in your strategy.
Customer Feedback Inflow
•	Explain your feedback collection system and how it's managed.
•	Describe how feedback is used to improve offerings and customer experience.
•	Emphasize your startup's responsiveness and adaptability.
-	-	-

`,
        image: "/Images/bplan/MarketAnalysis.jpg",
        // contentImage: "/Images/bplan/market-content.jpg",
      },
      {
        title: "Financials",
        content: `Revenue Sources
•	Identify the different sources of revenue in your business, including primary products/services, one-time offerings, and recurring income streams like subscriptions.
•	Break down the percentage of revenue generated by each source and explain strategies to optimize the effort-to-reward ratio for each.
•	Define which market segments are targeted by each revenue stream and justify the reasoning behind these choices.
•	Evaluate the profit generated per acquired customer per product over their lifetime, and explain how customer churn impacts this.
•	Outline the strategies you will implement to minimize churn and sustain long-term profitability.
Cost Structure 
•	List all major cost components, including recurring expenses (e.g., marketing, server maintenance), development costs, and infrastructure-related outflows.
•	Track the evolution of these costs over time to reflect business growth, scaling operations, and shifting priorities.
•	Account for asset depreciation and outline a plan for periodic reinvestment in essential equipment and resources.
•	Provide a clear breakdown of distribution, logistics, and employment-related expenses, particularly during the early stages of the business.
Financial Predictions
•	Present clear and well-explained financial statements, including a balance sheet, using the previously outlined revenue and cost figures to forecast near-future performance.
•	Define a strategy to increase profit margins by optimizing business costs and enhancing operational efficiency. Include scaling-related costs such as employment, and outline how tech or automation will maintain efficiency as the business grows.
•	State the initial funds or investment required (external or bootstrapped) and provide a detailed Return on Investment (ROI) plan for investors, including quarterly growth projections.
•	Show a comprehensive break-even analysis, detailing the business’s burn rate, the runway available with the current funding, and the estimated point at which the business will become profitable.
•	Build a long-term financial roadmap, listing key milestones to be reached within a realistic timeframe. Explain how these milestones will serve as pivot points and affect your financial trajectory.
•	Provide a cost-benefit analysis of the major milestones in your roadmap and explain how these milestones will impact the company’s financial health in the long term.
•	Break down financial projections into short-term (1–2 years) and long-term (5–10 years) timelines. Clearly specify whether the business is bootstrapped or seeking external funding and explain how this influences your financial outlook. 
Sustainability 
•	Assess how the business remains sustainable with market volatility. Account for financial risks (interest rate changes, market downfalls, or funding delays etc.).
•	Provide a detailed risk probability scoring and a numerical analysis of the impact with mitigation strategies. Include operational risks (supply chain disruptions, tech failures etc.).
Government Grants and Benefits:
•	List government grants and schemes that the business can leverage/benefit from.
•	Include tax benefits, regulatory advantages, and startup-friendly laws beyond just grants.
-	-	-

`,
        image: "/Images/bplan/MarketAnalysis.jpg",
        // contentImage: "/Images/bplan/product-content.jpg",
      },
      {
        title: "Research Paper",
        content: `A business has the capability to contribute to not just society, but to its own economic space, through research. This could either be through the means of R&D in their own product/service, revolutionizing the world one step at a time, or through research work related even remotely to their field, furthering the capabilities and knowledge of the market.
•	Provide a new concept not currently existing in the market or the economy (this could be a method to solve a problem, an unobserved trend, a concept or an idea) in the format of a research paper (for example, from the journal of EJMS).
•	Include a basic hypothesis, facts/statistics cited from other research papers, with references.
•	Conclude how they prove/disprove the initial hypothesis as the result, and how it affects the related field.
`,
        image: "/Images/bplan/MarketAnalysis.jpg",
        // contentImage: "/Images/bplan/entry-content.jpg",
      },
    ],
    []
  );

  return (
    <div className="min-h-screen bg-[#FCF5F0]">
      <Navbar textColor="#B63B2C" />

      <div className="max-w-7xl mx-auto px-4 pt-16 pb-24">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.1 }}
          className="text-center mb-12"
        >
          <h2
            className={`${helveticaCompressed.className} text-4xl md:text-5xl lg:text-6xl tracing-wide text-[#B63B2C] uppercase tracking-wide`}
          >
            Business Plan Guide
          </h2>
          <p
            className={`${bigShouldersDisplay.className} text-lg text-gray-700 mt-4 max-w-2xl mx-auto`}
          >
            Follow this comprehensive outline to create a professional business
            plan.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="flex justify-center mb-8"
        >
          <a
            href="/Images/bplan/B-Plan-Doc2.pdf"
            download
            className="flex items-center gap-2 bg-[#B63B2C] hover:bg-[#A32A1B] text-white py-3 px-6 rounded-sm transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              className="w-5 h-5"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
            <span
              className={`${bigShouldersDisplay.className} font-bold uppercase text-lg tracking-wide`}
            >
              Download B-Plan Doc
            </span>
          </a>
        </motion.div>

        {/* Section Navigation */}
        <div className="flex flex-wrap justify-center gap-2 mb-12">
          {bplanSections.map((section, index) => (
            <button
              key={index}
              onClick={() => setActiveSection(index)}
              className={`${
                bigShouldersDisplay.className
              } px-3 py-1 rounded-sm text-sm md:text-base transition-all duration-300 ${
                activeSection === index
                  ? "bg-[#B63B2C] text-white font-bold scale-110"
                  : "bg-white text-[#B63B2C] border font-bold  border-[#B63B2C] hover:bg-[#B63B2C]/10"
              }`}
            >
              {section.title}
            </button>
          ))}
        </div>

        {/* Active Section Display */}
        <motion.div
          key={activeSection}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          transition={{ duration: 0.5 }}
          className="bg-white rounded-sm shadow-lg overflow-hidden"
        >
          <div className="md:flex">
            {/* Image Section with Fallback */}
            <div className="md:w-1/2 h-64 md:h-auto">
              <div
                className="w-full h-full bg-cover bg-center"
                style={{
                  backgroundImage: `url(${bplanSections[activeSection].image})`,
                  backgroundColor: "#eed4ce",
                }}
              >
                {/* Fallback/overlay content */}
                <div className="flex items-center justify-center h-full w-full bg-[#eed4ce]/70">
                  <span
                    className={`${helveticaCompressed.className} text-[#B63B2C] text-2xl tracing-wide px-4 py-2 bg-white/80 rounded`}
                  >
                    {bplanSections[activeSection].title}
                  </span>
                </div>
              </div>
            </div>

            {/* Content Section */}
            <div className="md:w-1/2 p-6 md:p-8 overflow-y-auto max-h-[500px]">
              <h3
                className={`${helveticaCompressed.className} text-2xl md:text-3xl tracing-wide text-[#B63B2C] mb-4 sticky top-0 bg-white py-2 z-10`}
              >
                {bplanSections[activeSection].title}
              </h3>

              {/* Render formatted content */}
              {formatContent(bplanSections[activeSection].content)}

              {/* Section Progress Indicator */}
              <div className="mt-8 flex gap-1 justify-center">
                {bplanSections.map((_, index) => (
                  <div
                    key={index}
                    className={`h-1 rounded-full transition-all duration-300 ${
                      index === activeSection
                        ? "w-8 bg-[#B63B2C]"
                        : "w-2 bg-gray-300"
                    }`}
                  ></div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Tips Box */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.5 }}
          className="mt-12 bg-[#eed4ce] rounded-sm p-6 shadow-md"
        >
          <h3
            className={`${helveticaCompressed.className} text-xl text-[#B63B2C] mb-3`}
          >
            Tips for Evaluation 2:
          </h3>
          <ul
            className={`${bigShouldersDisplay.className} font-bold text-gray-800 space-y-2 list-disc pl-5`}
          >
            <li>
              You have 7 minutes for your pitch. Then 3 minutes will be given to
              the judges for quesitoning. That is it.
            </li>
            <li>Please go through the B-Plan Doc before pitching.</li>
            <li>Use clear, simple language and avoid industry jargon.</li>
            {/* <li>
              Include visuals like charts and graphs to illustrate key data
            </li>
            <li>
              Review and update your plan regularly as your business evolves
            </li>
            <li>Have trusted advisors review your plan before finalizing it</li> */}
          </ul>
        </motion.div>
      </div>

      <Footer textColor="#B63B2C" />
    </div>
  );
}
